---
networks:
  default:
    name: "eos"
services:
  eos:
    image: "akkudoktor/eos:${EOS_VERSION}"
    read_only: true
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        PYTHON_VERSION: "${PYTHON_VERSION}"
    env_file:
      - .env
    environment:
      - EOS_CONFIG_DIR=config
      - EOS_SERVER__EOSDASH_SESSKEY=s3cr3t
      - EOS_PREDICTION__LATITUDE=52.2
      - EOS_PREDICTION__LONGITUDE=13.4
      - EOS_ELECPRICE__PROVIDER=ElecPriceAkkudoktor
      - EOS_ELECPRICE__CHARGES_KWH=0.21
    ports:
      # Configure what ports to expose on host
      - "${EOS_SERVER__PORT}:8503"
      - "${EOS_SERVER__EOSDASH_PORT}:8504"
